"""fixed order and payment enum storage

Revision ID: d25f57bf9ab1
Revises: 84ad7d5c9f9b
Create Date: 2026-08-25 17:31:30.784270

"""
from alembic import op
import sqlalchemy as sa


revision = 'd25f57bf9ab1'
down_revision = '84ad7d5c9f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
